.catalog:
  name: "elk-stack"
  version: "v1.0"
  description: "Starting an ELK stack"
  uuid: elk-stack-1
logstash-indexer:
  metadata:
    logstash:
      inputs: |
        redis {
          host => "redis"
          port => "6379"
          data_type => "list"
          key => "logstash"
        }
      filters: |
        mutate {
          rename => { "docker.id" => "container_id" }
          rename => { "docker.name" => "container_name" }
          rename => { "docker.image" => "docker_image" }
          rename => { "docker.hostname" => "docker_hostname" }
        }
      outputs: |
        elasticsearch {
          hosts => ["elasticsearch:9200"]
        }
logstash-collector:
  metadata:
    logstash:
      inputs: |
        udp {
          port => 5000
          codec => "json"
        }
      outputs: |
        redis {
          host => "redis"
          port => "6379"
          data_type => "list"
          key => "logstash"
        }
logspout:
  scale: 1
elasticsearch:
  scale: 1
kibana-lb:
  scale: 1
nginx-proxy-conf:
  scale: 1
  metadata:
    nginx: &id001
      conf:
        servername: kibana
        upstream_port: 5601
      users:
        '0':
          username: admin
          password: '{PLAIN}rancher-elk-admin'
kibana:
  scale: 1
  metadata:
    nginx: *id001
nginx-proxy:
  scale: 1
  metadata:
    nginx: *id001
