version: '2'

services:
  gogs:
      image: gogs/gogs:latest
      ports:
          - ${http_port}:3000
          - ${ssh_port}:22
      links:
          - mysql:db

  mysql:
      image: mysql:latest
      ports:
          - ${public_port}:3306
      volumes:
          - gogs-nfs-volume:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: ${mysql_password}

volumes:
  gogs-nfs-volume:
    driver: rancher-nfs
    external: true
