version: '2'

services:
  nexus:
    image: sonatype/nexus3
    ports:
     - "7071:8081"
     - "18079:18079"
    volumes:
    - nexus:/nexus-data
    labels:
      io.rancher.container.pull_image: always

volumes:
  nexus:
    driver: rancher-nfs


